# Generated by Django 2.0.2 on 2018-02-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20180225_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_from', models.CharField(max_length=300)),
                ('address_to', models.CharField(max_length=300)),
                ('post_id', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='nano_address',
            old_name='imageUrl',
            new_name='address',
        ),
        migrations.AddField(
            model_name='nano_address',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
