# Generated by Django 2.0.2 on 2018-02-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20180225_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='raisedNano',
            field=models.FloatField(),
        ),
    ]
