# Generated by Django 2.0.2 on 2018-02-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_post_dumped'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='streetAddress',
            field=models.CharField(default='123', max_length=300),
            preserve_default=False,
        ),
    ]
