# Generated by Django 2.0.2 on 2018-02-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_post_streetaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
